[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
vector_xlite = "1.0.0"
rusqlite = { version = "0.37.0", features = ["load_extension" ]}
r2d2 = "0.8.10"
r2d2_sqlite = { version = "0.31.0"}

