name: Publish Crates

on:
  workflow_call:
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true

jobs:
  publish_crates:
    name: Publish Crates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Read Local vector_xlite Version
        id: local_vector_xlite_metadata
        working-directory: ./vector_xlite
        run: |
          LOCAL_VERSION=$(grep '^version' Cargo.toml | head -1 | sed 's/version = "//;s/"//')
          echo "version=$LOCAL_VERSION" | tee -a $GITHUB_OUTPUT

      - name: Fetch Remote vector_xlite version
        id: remote_vector_xlite_metadata
        run: |
          LATEST_VERSION=$(curl -H "User-Agent: github-vxlite-wf" \
          -s https://crates.io/api/v1/crates/vector_xlite \
            | jq -r '.crate.max_stable_version')

          echo "version=$LATEST_VERSION" | tee -a $GITHUB_OUTPUT

      - name: Publish Vector xLite
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        # if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
        # if: ${{ steps.local_vector_xlite_metadata.outputs.version }} > ${{ steps.remote_vector_xlite_metadata.outputs.version }}
        run: |
          LOCAL=${{ steps.local_vector_xlite_metadata.outputs.version }}
          REMOTE=${{ steps.remote_vector_xlite_metadata.outputs.version }}
  
          LATEST=$(printf '%s\n%s' "$REMOTE" "$LOCAL" | sort -V | tail -n1)

          if [ "$LATEST" = "$LOCAL" ] && [ "$LOCAL" != "$REMOTE" ]; then
            echo "publish=true"
          else
            echo "publish=false"
          fi
        # cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        working-directory: ./vector_xlite
        

