name: Vector XLite CI Pipeline

on :
  workflow_dispatch:
    
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_rust_projects:
    uses: ./.github/workflows/ci-rust.yml
    secrets: inherit
  
  build_go_proejects:
    uses: ./.github/workflows/ci-go.yml