name: Build and Test Rust Projects
on:
  workflow_call:

jobs:
  build_rust:
    name: Build and Test Rust Projects
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Build Vector XLite Crate
        run : cargo build --release
        working-directory: ./vector_xlite
      
      - name: Build Vector XLite Tests
        run : cargo build --release
        working-directory: ./vector_xlite_tests

      - name: Install cargo NextTest
        run : cargo install cargo-nextest

      - name: Run Vector XLite Tests
        run : cargo nextest run --no-fail-fast --jobs=1
        working-directory: ./vector_xlite_tests

      - name: Build Vector XLite Examples
        run : cargo build --release
        working-directory: ./console_exmples/rust_examples

      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Build Vector XLite gRPC Server
        run : cargo build --release
        working-directory: ./vector_xlite_grpc_server

