name: Build and Test Rust Projects
on:
  workflow_call:

jobs:
  build:
    name: Build and Test Rust Projects
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Build Vector XLite Crate
        run : cargo build --release
        working-directory: ./vector_xlite
      
      - name: Build Vector XLite Tests
        run : cargo build --release
        working-directory: ./vector_xlite_tests

      - name: Run Vector XLite Tests
        run : cargo test
        working-directory: ./vector_xlite_tests

      - name: Build Vector XLite Examples
        run : cargo build --release
        working-directory: ./console_exmples/rust_examples
    
      - name: Build Vector XLite gRPC Server
        run : cargo build --release
        working-directory: ./vector_xlite_grpc_server

