name: Build and Test Rust Projects
on:
  workflow_call:

jobs:
  build_rust:
    name: Build and Test Rust Projects
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Build Vector XLite Crate
        run : cargo build --release
        working-directory: ./vector_xlite
      
      - name: Build Vector XLite Tests
        run : cargo build --release
        working-directory: ./vector_xlite_tests

      - name: Run Vector XLite Tests
        run : cargo test
        working-directory: ./vector_xlite_tests

      - name: Build Vector XLite Examples
        run : cargo build --release
        working-directory: ./console_exmples/rust_examples

      # Publish only on push to main
      - name: Publish Vector XLite Crate
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        working-directory: ./vector_xlite
        run: echo "${{ secrets.CARGO_REGISTRY_TOKEN }}"
      
      # Publish only on push to main
      - name: Publish Vector XLite Crate1
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        working-directory: ./vector_xlite
        run: echo "$CARGO_REGISTRY_TOKEN"

      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Build Vector XLite gRPC Server
        run : cargo build --release
        working-directory: ./vector_xlite_grpc_server

